### ISSUE TITLE
Add Support for bank code 846

### ISSUE THREAD

**Issue by Nushio** [center-key/clabe-validator#10]
846: 'Sistema de Transferencias y Pagos STP',

Hi! I can send a PR if needed but wanted to discuss this first. We've been working with STP, and they have a secondary Bank Code, which I believe they only use for tests. The problem is that they do have "valid clabes" but the CLABE Validator says it's not valid because it starts with 846.

Thoughts? Thanks!

**Comment by pilafmon** [comment]
It's important to support bank codes that are actually being used.  Obviously the banks on the original list created by the ABM are valid, but it also seems new codes come into existence without officially being published anywhere.

Anyway, adding the `846` code seems totally reasonable.  Go for it!

**Comment by Nushio** [comment]
Thanks! I've opened a PR with the change! :-)

**Comment by pilafmon** [comment]
Release v1.2.1
