### ISSUE TITLE
Problem with cities

### ISSUE THREAD

**Issue by medisoft** [center-key/clabe-validator#16]
Hi! This clabe 646521162218542788 is not working because the city is not in the list.

It could be a good idea to allow validation of bank only.

**Comment by pilafmon** [comment]
What is the name of the city for code 521?

**Comment by pilafmon** [comment]
If you call `clabe.validate('646521162218542788')`, it will return:

```javasscript
{
   account:  '16221854278',
   bank:     'Sistema de Transferencias y Pagos STP, S.A. de C.V., SOFOM E.N.R.',
   checksum: 8,
   city:     undefined,
   code:     { bank: '646', city: '521' },
   error:    'invalid-city',
   formatOk: true,
   message:  'Invalid city code: 521',
   ok:       false,
   tag:      'STP'
}
```

You can check the `bank` field to see if the **bank code** is valid even if the **city code** is invalid.  Also, the `formatOk` field can be `true` even if the **bank code** and **city code** are unknown.

**Comment by pilafmon** [comment]
If you ever want the city code added, just reopen this issue or submit a pull request.
