### ISSUE TITLE
Update travis ci to node v12

### ISSUE THREAD

**Issue by pilafmon** [center-key/clabe-validator#17]
Time for v12:
https://nodejs.org/en/about/releases/

See:
[.travis.yml](../blob/master/.travis.yml)

**Comment by MykolaKolotylo** [comment]
@dpilafian Can I try to do it as my first issue?

**Comment by MykolaKolotylo** [comment]
@dpilafian created a PR, please take a look https://github.com/center-key/clabe-validator/pull/26
