### ISSUE TITLE
Switch to ES6 object method shorthand in clabe.js

### ISSUE THREAD

**Issue by pilafmon** [center-key/clabe-validator#18]
Upgrade to more modern ES6 function definitions. The newer notation is more compact and looks better.

See **MDN web docs**:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

**Comment by pilafmon** [comment]
For example, change:
```javascript
   computeChecksum: (clabeNum17) => {
```
to:
```javascript
   computeChecksum(clabeNum17) {
```
and then make sure all the tests pass: `$ npm test`

**Comment by wejrox** [comment]
Hey, I can do this one but could you register your repository with HacktoberFest by adding the `hacktoberfest` topic to your repository?
