### ISSUE TITLE
Please add Hacktoberfest topic to the repo

### ISSUE THREAD

**Issue by wejrox** [center-key/clabe-validator#29]
If you add the `hacktoberfest` topic to the repository, more contributors will address the issues available.

**Comment by pilafmon** [comment]
Cool, thanks for the suggestion.

I also added the topic to some other projects:
* [dna.js](https://github.com/dnajs/dna.js)
* [fetch-json](https://github.com/center-key/fetch-json)
* [pretty-print-json](https://github.com/center-key/pretty-print-json)
