### ISSUE TITLE
Unable to use ir on a React.js project

### ISSUE THREAD

**Issue by JMGama** [center-key/clabe-validator#36]
Hi ✋ 
I'm trying to use this in my reactjs project to validate de CLABE in the front-end, but when I try tu use it throws the next error:
`Unhandled Rejection (TypeError): Cannot read property 'validate' of undefined`
I'm trying to use it exactly as the README say.
```
import { clabe } from "clabe-validator";
----

const clabeNum = "002010077777777771";
const clabeCheck = clabe.validate(clabeNum);
console.log(clabeCheck);
```

**Comment by pilafmon** [comment]
The error message means that `clabe` is not set  at all, which implies that the `import` statement did not work.

Make sure you have the latest version installed:
```
npm install clabe-validator@latest
```
Then add a simple debug line to verify the `import` statement is working:
```javascript
console.log(clabe);
```

**Comment by JoseOrtiz** [comment]
Same here, on a VueJs project, `clabe` is undefined and this is an error 
```can't access property "validate", clabe_validator__WEBPACK_IMPORTED_MODULE_4__.clabe is undefined```

**Comment by pilafmon** [comment]
@JoseOrtiz It's possible that WebPack is confused.  Maybe you need to put the **clabe-validator** import statement earlier.  Another Vue user had a similar problem: https://stackoverflow.com/a/35240717/1553812

What does your import look like in Vue?  Are you using the old CommonJS/UMD `require` statements or the new ES6 module `import` statements?  I'm not familiar with Vue, so I'm not even sure exactly what questions to ask.

**clabe-validator** is configured to support both the old CommonJS/UMD and the new ES6 Modules:
```
   "main": "dist/clabe.umd.cjs",
   "module": "dist/clabe.esm.js",
```
https://github.com/center-key/clabe-validator/blob/master/package.json#L7-L8

You may even want to post a question on StackOverflow -- sometimes you can get surprisingly fast answers there.

**Comment by chimilord** [comment]
Hi @JMGama, I have the same problem on a React app, did you find any workaround? Thanks.

**Comment by JNeutron** [comment]
> Hi @JMGama, I have the same problem on a React app, did you find any workaround? Thanks.

I solved importing like this in a Vue project: 

`import { clabe } from 'clabe-validator/dist/clabe.esm'`

**Comment by docdrue** [comment]
> The error message means that `clabe` is not set at all, which implies that the `import` statement did not work.
> 
> Make sure you have the latest version installed:
> 
> ```
> npm install clabe-validator@latest
> ```
> 
> Then add a simple debug line to verify the `import` statement is working:
> 
> ```js
> console.log(clabe);
> ```

Only this works for React project 
`import { clabe } from 'clabe-validator/dist/clabe.esm';`

**Comment by pilafmon** [comment]
Release v1.6.6
