### ISSUE TITLE
Invalid city code: 969

### ISSUE THREAD

**Issue by tuxity** [center-key/clabe-validator#40]
Hello,

Just wanted to report an error I noticed while trying to validate an NVIO CLABE (e.g. `710969000000000004`). I get the error `Invalid city code: 969` when I'm sure the clabe is 100% correct and working because it's being used for transfer.

Thanks!

**Comment by pilafmon** [comment]
What is the **city and state in Mexico** where the branch is located for the bank account?

It will be just a single line of code to add the `969` city.

If you want, you can submit a PR to add the city into the `cities` array at:
https://github.com/center-key/clabe-validator/blob/main/clabe.ts#L1122

**Comment by pilafmon** [comment]
I just realized that NVIO (NVIO Pagos México) is not a traditional bank.

However, the company is [headquartered](https://www.dnb.com/business-directory/company-profiles.nvio_pagos_méxico_sapi_de_cv_ifpe.04ca98517ab2ee5948c9e289f503a4b5.html) in Mexico City, so it seems an appropriate name for the CLABE city code `969` would be: **Ciudad de México (MX-CMX)**

```typescript
      [969, 'Ciudad de México', 'MX-CMX'],
```

**Comment by tuxity** [comment]
They are an IFPE among others https://www.cnbv.gob.mx/Entidades-Autorizadas/Paginas/FondosPagoElectronico.aspx
I don't have accounts to check the clabe of other entities to see if it's the same unfortunately
